### ISSUE TITLE
How to setup tag `{{ now }}` in my template

### ISSUE THREAD

**Issue by zentala** [RoadieHQ/software-templates#45]
In your templates you are using tag `now`, eg:
```branchName: onboard-to-catalog-${{ '' | now }}```

But it is not suporrted by Backstage and it is not part of https://mozilla.github.io/nunjucks/templating.html#file-extensions.

How did you setup? As custom template filter or there is other way? I think this is not a filter... 

P.

**Comment by iain-b** [comment]
Yes this is implemented as a custom filter. You're correct it's not a filter, probably should have been added as a global. I believe the Backstage scaffolder accepts an option `additionalTemplateFilters` which we used to set this but you/we could use `additionalTemplateGlobals` instead.

**Comment by zentala** [comment]
For others in the future - this worked for me:

```
const scaffolderModuleCustomFilters = createBackendModule({
  pluginId: 'scaffolder', // name of the plugin that the module is targeting
  moduleId: 'custom-filters',
  register(env) {
    env.registerInit({
      deps: {
        scaffolder: scaffolderTemplatingExtensionPoint
      },
      async init({ scaffolder }) {
        scaffolder.addTemplateFilters({
          now: () => new Date().getTime().toString()
        })
      }
    })
  }
})

...

  backend.add(scaffolderModuleCustomFilters())
```


Must to remember that this is filter, so use it like one:

```${ '' | now }```

(it replaces empty string with new timestamp)
